<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Mediator\Appointment\Command\SavePurchaseInvoiceWHTCommand.cs" />
    <Compile Remove="Mediator\Appointment\Handler\ApproveGRNHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\ApprovePurchaseInvoiceHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\DeleteGRNHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\GetAllGRNHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\GetAllPurchaseInvoiceHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\GetGRNByIdHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\GetGRNCodeHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\GetGRNCountHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\GetPendingCostSheetHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\GetPendingInspectionItemsHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\GetPendingInspectionsHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\GetPurchaseInvoiceCountHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\ProcessGRNHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\ProcessPurchaseInvoiceHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\RejectPurchaseInvoiceHandler.cs" />
    <Compile Remove="Mediator\Appointment\Handler\SavePurchaseInvoiceWHTHandler.cs" />
    <Compile Remove="Mediator\Appointment\Query\ApproveGRNQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\ApprovePurchaseInvoiceQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\DeleteGRNQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\GetAllGRNQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\GetAllPurchaseInvoiceQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\GetGRNByIdQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\GetGRNCodeQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\GetGRNCountQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\GetPendingCostSheetQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\GetPendingInspectionsItemsQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\GetPendingInspectionsQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\GetPurchaseInvoiceCountQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\ProcessGRNQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\ProcessPurchaseInvoiceQuery.cs" />
    <Compile Remove="Mediator\Appointment\Query\RejectPurchaseInvoiceQuery.cs" />
    <Compile Remove="Mediator\Item\Handler\GetItemByNameWarehouseHandler.cs" />
    <Compile Remove="Mediator\Item\Query\GetItemByNameWarehouseQuery.cs" />
    <Compile Remove="Mediator\PurchaseOrder\Handler\GetPendingDemandQuery.cs" />
    <Compile Remove="Mediator\TransferRequest\Command\AuthorityCommand.cs" />
    <Compile Remove="Mediator\TransferRequest\Command\DealerCommand.cs" />
    <Compile Remove="Mediator\TransferRequest\Command\MemberCommand.cs" />
    <Compile Remove="Mediator\TransferRequest\Command\SaveTransferCommand.cs" />
    <Compile Remove="Mediator\TransferRequest\Command\SocietyCommand.cs" />
    <Compile Remove="Mediator\TransferRequest\Command\TransferSellerBuyerInfoCommand.cs" />
    <Compile Remove="Mediator\TransferRequest\Command\TransferSellerBuyerPictureCommand.cs" />
    <Compile Remove="Mediator\TransferRequest\Handler\GetDealerHandler.cs" />
    <Compile Remove="Mediator\TransferRequest\Handler\GetFileHandler.cs" />
    <Compile Remove="Mediator\TransferRequest\Handler\GetSellerBuyerByIdHandler.cs" />
    <Compile Remove="Mediator\TransferRequest\Handler\GetSellerBuyerHandler.cs" />
    <Compile Remove="Mediator\TransferRequest\Handler\GetSocietiesHandler.cs" />
    <Compile Remove="Mediator\TransferRequest\Handler\SaveTransferHandler.cs" />
    <Compile Remove="Mediator\TransferRequest\Query\GetDealerQuery.cs" />
    <Compile Remove="Mediator\TransferRequest\Query\GetFileQuery.cs" />
    <Compile Remove="Mediator\TransferRequest\Query\GetSellerBuyerByIdQuery.cs" />
    <Compile Remove="Mediator\TransferRequest\Query\GetSellerBuyerQuery.cs" />
    <Compile Remove="Mediator\TransferRequest\Query\GetSocietiesQuery.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="10.3.0" />
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Polybioz.HtmlRenderer.PdfSharp.Core" Version="1.0.0" />

    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.12.1" />
    <PackageReference Include="Stripe.net" Version="39.63.0" />
    <PackageReference Include="Twilio" Version="5.65.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERP.Core\ERP.Core.csproj" />
    <ProjectReference Include="..\ERP.Entities\ERP.Entities.csproj" />
    <ProjectReference Include="..\ERP.Services\ERP.Services.csproj" />
    <ProjectReference Include="..\ERP.Services\ERP.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mediator\Dashboard\Command\" />
    <Folder Include="Mediator\Doctor\Command\" />
    <Folder Include="Mediator\Email\Command\" />
    <Folder Include="Mediator\Employee\Command\" />
    <Folder Include="Mediator\Ledger\Command\" />
    <Folder Include="Mediator\User\Validator\" />
    <Folder Include="Dll\" />
  </ItemGroup>

</Project>
